### ISSUE TITLE
Respawn Event Listener

### ISSUE THREAD

**Issue by endercrest** [ClickPT/EasySetSpawn#1]
https://github.com/ClickPT/EasySetSpawn/blob/master/src/me/clickpt/easysetspawn/Events.java#L128-L135

In the respawn event listener you are delaying the teleportation by 5 ticks. However, this is bad practice as this will always override another listener for respawning that might have a higher priority. You should be using the setRespawnLocation method for the event.

**Comment by ClickPT** [comment]
Thanks for advising. I will fix it in possible future update.

**Comment by ClickPT** [comment]
Fixed in the new update (2.1).
